# Generated by Django 5.1.3 on 2024-12-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('leave_type', models.CharField(choices=[('Unpaid Leave', 'Unpaid Leave'), ('Annual Leave', 'Annual Leave'), ('Sick Leave', 'Sick Leave'), ('Unknown', 'Unknown')], default='Annual Leave')),
                ('status', models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Requested', null=True)),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
