# Generated by Django 5.1.3 on 2024-12-26 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_leaverequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='00', max_length=100)),
                ('bank_branch_location', models.CharField(default='Kathmandu', max_length=50)),
                ('employee_bank_account_name', models.CharField(default=0, max_length=100)),
                ('employee_bank_account_number', models.CharField(default=0, max_length=50)),
                ('employee_pan_number', models.PositiveBigIntegerField(default=0)),
                ('employee_pan_photo', models.ImageField(blank=True, default=None, null=True, upload_to='EmployeePanCard/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.CharField(default=11, unique=True)),
                ('job_title', models.CharField(default='employee', max_length=200)),
                ('phone_number', models.CharField(default=0, max_length=10, unique=True)),
                ('date_of_birth', models.CharField(default='2025/10/10')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='00')),
                ('employee_citizenship_number', models.CharField(default=0, max_length=14)),
                ('employee_citizenship_photo', models.ImageField(blank=True, null=True, upload_to='EmployeeCitizenship/')),
                ('employee_resume_pdf', models.FileField(blank=True, null=True, upload_to='EmployeeResume/')),
                ('employee_pp_photo', models.ImageField(blank=True, null=True, upload_to='EmployeePhoto/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
