# Generated by Django 5.1.3 on 2024-12-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Unpaid Leave', 'Unpaid Leave'), ('Sick Leave', 'Sick Leave'), ('Annual Leave', 'Annual Leave')], default='Annual Leave'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Requested', null=True),
        ),
    ]
