# Generated by Django 5.1.3 on 2024-12-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_leaverequest_leave_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Unpaid Leave', 'Unpaid Leave'), ('Annual Leave', 'Annual Leave'), ('Sick Leave', 'Sick Leave')], default='Annual Leave'),
        ),
    ]
