# Generated by Django 5.1.3 on 2024-12-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_bankdetails_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('time_duration', models.CharField(max_length=100)),
            ],
        ),
    ]
